public enum Status
{
    STATUS_OK = 200,
    STATUS_TIMEOUT = 504,
    STATUS_UNAUTHORIZED = 401,
    STATUS_NOT_FOUND = 404,
    STATUS_DUPLICATE = 409,
    STATUS_FAILED = 500,
    STATUS_NOT_PERMITTED = 400
}